import {
  LAYOUT_PROFILE_ID,
  type LayoutDefinitionV1,
  type LayoutProfileId,
} from "./types";

function freezeDefinition(def: LayoutDefinitionV1): LayoutDefinitionV1 {
  return Object.freeze({
    ...def,
    steps: Object.freeze(def.steps.map((step) => Object.freeze({ ...step }))),
  });
}

export const MACOS_US_INTERNATIONAL_DEFINITION: LayoutDefinitionV1 =
  freezeDefinition({
    schemaVersion: 1,
    definitionId: "macos-us-international-calibration",
    layoutProfileId: LAYOUT_PROFILE_ID.MACOS_US_INTERNATIONAL,
    version: 1,
    steps: [
      {
        id: "accent-acute-a",
        mandatory: true,
        code: "KeyA",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "á",
        allowComposition: true,
      },
      {
        id: "letter-enye",
        mandatory: true,
        code: "KeyN",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "ñ",
        allowComposition: true,
      },
      {
        id: "letter-udiaeresis",
        mandatory: true,
        code: "KeyU",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "ü",
        allowComposition: true,
      },
      {
        id: "punctuation-open-question",
        mandatory: true,
        code: "Slash",
        altKey: true,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "¿",
        allowComposition: false,
      },
      {
        id: "punctuation-question",
        mandatory: true,
        code: "Slash",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "?",
        allowComposition: false,
      },
      {
        id: "punctuation-open-exclamation",
        mandatory: true,
        code: "Digit1",
        altKey: true,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "¡",
        allowComposition: false,
      },
      {
        id: "punctuation-exclamation",
        mandatory: true,
        code: "Digit1",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "!",
        allowComposition: false,
      },
    ],
  });

export const MACOS_LATIN_AMERICAN_QWERTY_DEFINITION: LayoutDefinitionV1 =
  freezeDefinition({
    schemaVersion: 1,
    definitionId: "macos-latin-american-qwerty-calibration",
    layoutProfileId: LAYOUT_PROFILE_ID.MACOS_LATIN_AMERICAN_QWERTY,
    version: 1,
    steps: [
      {
        id: "accent-acute-a",
        mandatory: true,
        code: "KeyA",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "á",
        allowComposition: true,
      },
      {
        id: "letter-enye",
        mandatory: true,
        code: "Semicolon",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "ñ",
        allowComposition: false,
      },
      {
        id: "letter-udiaeresis",
        mandatory: true,
        code: "KeyU",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "ü",
        allowComposition: true,
      },
      {
        id: "punctuation-open-question",
        mandatory: true,
        code: "Equal",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "¿",
        allowComposition: false,
      },
      {
        id: "punctuation-question",
        mandatory: true,
        code: "Minus",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "?",
        allowComposition: false,
      },
      {
        id: "punctuation-open-exclamation",
        mandatory: true,
        code: "Equal",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "¡",
        allowComposition: false,
      },
      {
        id: "punctuation-exclamation",
        mandatory: true,
        code: "Digit1",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "!",
        allowComposition: false,
      },
    ],
  });

export const WINDOWS_US_INTERNATIONAL_DEFINITION: LayoutDefinitionV1 =
  freezeDefinition({
    schemaVersion: 1,
    definitionId: "windows-us-international-calibration",
    layoutProfileId: LAYOUT_PROFILE_ID.WINDOWS_US_INTERNATIONAL,
    version: 1,
    steps: [
      {
        id: "accent-acute-a",
        mandatory: true,
        code: "KeyA",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "á",
        allowComposition: true,
      },
      {
        id: "letter-enye",
        mandatory: true,
        code: "KeyN",
        altKey: true,
        ctrlKey: true,
        metaKey: false,
        shiftKey: false,
        expected: "ñ",
        allowComposition: false,
      },
      {
        id: "letter-udiaeresis",
        mandatory: true,
        code: "KeyU",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "ü",
        allowComposition: true,
      },
      {
        id: "punctuation-open-question",
        mandatory: true,
        code: "Slash",
        altKey: true,
        ctrlKey: true,
        metaKey: false,
        shiftKey: false,
        expected: "¿",
        allowComposition: false,
      },
      {
        id: "punctuation-question",
        mandatory: true,
        code: "Slash",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "?",
        allowComposition: false,
      },
      {
        id: "punctuation-open-exclamation",
        mandatory: true,
        code: "Digit1",
        altKey: true,
        ctrlKey: true,
        metaKey: false,
        shiftKey: false,
        expected: "¡",
        allowComposition: false,
      },
      {
        id: "punctuation-exclamation",
        mandatory: true,
        code: "Digit1",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "!",
        allowComposition: false,
      },
    ],
  });

export const WINDOWS_LATIN_AMERICAN_QWERTY_DEFINITION: LayoutDefinitionV1 =
  freezeDefinition({
    schemaVersion: 1,
    definitionId: "windows-latin-american-qwerty-calibration",
    layoutProfileId: LAYOUT_PROFILE_ID.WINDOWS_LATIN_AMERICAN_QWERTY,
    version: 1,
    steps: [
      {
        id: "accent-acute-a",
        mandatory: true,
        code: "KeyA",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "á",
        allowComposition: true,
      },
      {
        id: "letter-enye",
        mandatory: true,
        code: "Semicolon",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "ñ",
        allowComposition: false,
      },
      {
        id: "letter-udiaeresis",
        mandatory: true,
        code: "KeyU",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "ü",
        allowComposition: true,
      },
      {
        id: "punctuation-open-question",
        mandatory: true,
        code: "Equal",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: false,
        expected: "¿",
        allowComposition: false,
      },
      {
        id: "punctuation-question",
        mandatory: true,
        code: "Minus",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "?",
        allowComposition: false,
      },
      {
        id: "punctuation-open-exclamation",
        mandatory: true,
        code: "Equal",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "¡",
        allowComposition: false,
      },
      {
        id: "punctuation-exclamation",
        mandatory: true,
        code: "Digit1",
        altKey: false,
        ctrlKey: false,
        metaKey: false,
        shiftKey: true,
        expected: "!",
        allowComposition: false,
      },
    ],
  });

export const KEYBOARD_DEFINITIONS: Record<LayoutProfileId, LayoutDefinitionV1> =
  Object.freeze({
    [LAYOUT_PROFILE_ID.MACOS_US_INTERNATIONAL]:
      MACOS_US_INTERNATIONAL_DEFINITION,
    [LAYOUT_PROFILE_ID.MACOS_LATIN_AMERICAN_QWERTY]:
      MACOS_LATIN_AMERICAN_QWERTY_DEFINITION,
    [LAYOUT_PROFILE_ID.WINDOWS_US_INTERNATIONAL]:
      WINDOWS_US_INTERNATIONAL_DEFINITION,
    [LAYOUT_PROFILE_ID.WINDOWS_LATIN_AMERICAN_QWERTY]:
      WINDOWS_LATIN_AMERICAN_QWERTY_DEFINITION,
  });
